### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by mctrivia** [nemosminer/NemosMiner#814]
I keep getting the below.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Management.Automation.CommandNotFoundException: The term 'out-file' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at <ScriptBlock><trap>(Closure , FunctionContext )
   at System.Management.Automation.ExceptionHandlingOps.ProcessTraps(FunctionContext funcContext, RuntimeException rte)
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at <ScriptBlock>(Closure , FunctionContext )
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeAsDelegateHelper(Object dollarUnder, Object dollarThis, Object[] args)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by nemosminer** [comment]
ok i have test rigs running v3.4.2  since release coming up 7days now no crash for me and my rigs...

**Comment by grantemsley** [comment]
I have had this happen, only once, on one of my miners.  It froze/crashed the GUI but the background jobs and runspaces kept going, mining and switching kept running just fine.

I just assumed a hardware glitch, and it's been fine ever since, but if it happens again I'll try to investigate further.

**Comment by nemosminer** [comment]
i have had people post this same issue before... but when i try to replicate this on my rigs i am unable to so..

**Comment by grantemsley** [comment]
Yeah.  Seems it's probably rare enough to be nearly impossible to troubleshoot.  But like I said, if it happens for me again I'll see what I can figure out.

**Comment by mctrivia** [comment]
happens daily for me.  auto switching keeps going though both the dos prompt where it shows checking pool stats and the gui both stall.

may be me.  i can't get eth hash to run either.

**Comment by nemosminer** [comment]
daily yeh your rig  sounds broken... 

ethash runs fine on 1060 6gb and above...

my 1st 2080 's just turned up this morning so busy 2day ...

**Comment by mctrivia** [comment]
ah.  i have a 1060 3GB which at least explains the eth hash.

the 2080 is a beautiful card but is it really worth buying new hardware any more unless its an ASIC?

**Comment by nemosminer** [comment]
efficiency is key for me not price... 

selling all my 1080ti's 1070ti's 1070's and buying 2080's

**Comment by mctrivia** [comment]
fair enough.  my hydro is free(solar) and it is cold 8 months of year.  just have 1 card because i need for rendering stuff anyways.  mine the rest of time for a bit of extra heat/coins.

**Comment by nemosminer** [comment]
got it on a test rig

**Comment by petrovsky34** [comment]
sometimes it starts two miners work

**Comment by nemosminer** [comment]
testing v3.5 so far so good 18hours running

**Comment by grantemsley** [comment]
Happened to me on one of my machines today.  

The part it's complaining about is the trap in $TimerUI.Add_Tick - third line of the exception message says it happened in a trap in a script block, and that's the only place trap is used at all.

The UI dies - doesn't refresh anymore, buttons don't work.  But all the other threads (the core cycle, idle monitoring, earnings tracker, brainplus, etc) keep running just fine. Which means it won't affect your mining or profitability at all, making it annoying rather than show stopping.

But the code for the trap is perfectly fine.  It complaining Out-File isn't a valid command seems to indicate something's gone wrong with powershell itself by that point.  Unfortunately I haven't figured out any way to get it to show us the actual error trap is catching, since powershell is broken at at that point.  Still thinking about it.

```
System.Management.Automation.CommandNotFoundException: The term 'out-file' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at <ScriptBlock><trap>(Closure , FunctionContext )
   at System.Management.Automation.ExceptionHandlingOps.ProcessTraps(FunctionContext funcContext, RuntimeException rte)
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at <ScriptBlock>(Closure , FunctionContext )
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeAsDelegateHelper(Object dollarUnder, Object dollarThis, Object[] args)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```
